/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("io.prestosql:presto-spi:318")
    implementation("io.airlift:log:0.163")
    implementation("org.komamitsu:fluency:1.7.0")
    implementation("com.google.guava:guava:21.0")
}

group = "fluentd"
version = "0.0.6"
description = "presto-fluentd"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
